import type { Metadata } from 'next';
import { Fira_Code, Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/components/main/Header';
import { ThemeProvider } from 'next-themes';

const fira_code = Fira_Code({
  variable: '--font-fira-code',
  subsets: ['latin'],
});

const geistSans = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
});

const geistMono = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fira_code.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <section className="relative min-h-screen flex flex-col bg-gradient-to-br from-blue-100 via-purple-50/50 to-pink-200 dark:from-blue-950/50 dark:via-purple-950/10 dark:to-pink-950/20 transition-colors duration-500">
            <Header />
            {children}
          </section>
        </ThemeProvider>
      </body>
    </html>
  );
}
